spring:
  datasource:
    dynamic:
      enabled: true #启用动态数据源，默认true
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      grace-destroy: false #是否优雅关闭数据源，默认为false，设置为true时，关闭数据源时如果数据源中还存在活跃连接，至多等待10s后强制关闭
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/cn_db?serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/en_db?serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  # MyBatis-Plus Mapper XML文件路径配置
  mapper-locations: classpath*:/org/example/mapper/*Mapper.xml,classpath*:mapper/*.xml,classpath*:/mappers/*.xml
  # MyBatis-Plus 类型别名包配置
  typeAliasesPackage: org.example
  global-config:
    # 全局配置：数据库字段下划线映射驼峰配置
    db-column-underline: true
    db-config:
      # 字段策略配置
      id-type: "ASSIGN_ID"
      # 逻辑删除标记值配置
      field-strategy: 2
      # 逻辑未删除标记值配置
      logic-delete-value: floor(extract(epoch from now()))
  configuration:
    # 将数据库列名映射为驼峰命名配置
    map-underscore-to-camel-case: true
    # 缓存是否启用配置
    cache-enabled: false
    # 空值jdbc类型配置
    jdbc-type-for-null: 'null'
